---
- hosts: ubuntu-tests
  sudo: true
  roles:
  - basic
  tasks:
     - name: Install Package
       apt: name=apache2 state=installed
       notify: restart apache
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
- hosts: all
  roles: 
  - webserver
